"""Offsite, encrypted backups of the database.

The database already has daily local backups with a restore test (app/ops.py). That protects against a mistake or corruption, NOT against losing the
volume or the hosting account. This module copies the newest verified backup somewhere else, encrypted so that the storage provider (and anyone who
gets the storage key) can read nothing.

Design (see docs/PLATFORM_NOTES.md section 3):
  * Hybrid encryption: a random AES-256-GCM key encrypts the backup; that key is wrapped with an RSA-4096 PUBLIC key (OAEP, SHA-256). The server holds only
    the public key, so a stolen server or storage key cannot decrypt old backups. The private key is generated by scripts/make_backup_keys.py and kept offline.
  * A destination is anything with put/get/list/delete: an S3-compatible bucket (AWS S3, Backblaze B2, Cloudflare R2; signed with AWS Signature V4 over
    httpx, no SDK) or a local folder (tests, or a mounted drive).
  * Objects are named by date; the newest 30 daily and 12 monthly copies are kept.
  * "Backed up offsite" is only reported after the object is listed back at the expected size. A restore is a separate, rehearsed step
    (scripts/restore_offsite.py): download, decrypt, integrity check.

Configuration (Fly secrets; nothing is read from the repository): OFFSITE_BACKUP_PUBLIC_KEY (PEM) plus either OFFSITE_BACKUP_DIR (a folder) or
OFFSITE_S3_ENDPOINT, OFFSITE_S3_BUCKET, OFFSITE_S3_REGION, OFFSITE_S3_KEY_ID, OFFSITE_S3_SECRET (use a key that can only write and list, never delete,
if the provider allows it; pruning then needs a separate key and is skipped).
"""
from __future__ import annotations

import datetime as dt
import hashlib
import hmac
import logging
import os
import re
import struct
import urllib.parse
from pathlib import Path
from typing import Protocol

import httpx
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

logger = logging.getLogger("callkettle.offsite")

MAGIC = b"CKB1"
KEEP_DAILY, KEEP_MONTHLY = 30, 12


# ---------------------------------------------------------------------------------------------------------- keys and encryption
def generate_keypair() -> tuple[bytes, bytes]:
    """(private_pem, public_pem). The private key is shown once, to the owner, and never stored on the server."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=4096)
    private = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())
    public = key.public_key().public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    return private, public


_OAEP = padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None)


def encrypt(plaintext: bytes, public_pem: bytes) -> bytes:
    public = serialization.load_pem_public_key(public_pem)
    data_key, nonce = AESGCM.generate_key(bit_length=256), os.urandom(12)
    wrapped = public.encrypt(data_key, _OAEP)
    body = AESGCM(data_key).encrypt(nonce, plaintext, MAGIC)          # the header is authenticated, so a swapped header fails to decrypt
    return MAGIC + struct.pack(">H", len(wrapped)) + wrapped + nonce + body


def decrypt(blob: bytes, private_pem: bytes) -> bytes:
    if blob[:4] != MAGIC:
        raise ValueError("not an encrypted backup (bad header)")
    (n,) = struct.unpack(">H", blob[4:6])
    wrapped, nonce, body = blob[6:6 + n], blob[6 + n:18 + n], blob[18 + n:]
    private = serialization.load_pem_private_key(private_pem, password=None)
    data_key = private.decrypt(wrapped, _OAEP)
    return AESGCM(data_key).decrypt(nonce, body, MAGIC)


# ---------------------------------------------------------------------------------------------------------- destinations
class Destination(Protocol):
    def put(self, name: str, data: bytes) -> None: ...
    def get(self, name: str) -> bytes: ...
    def list(self, prefix: str = "") -> list[tuple[str, int]]: ...      # (name, size)
    def delete(self, name: str) -> None: ...


class LocalFolder:
    """A folder (tests, or a mounted drive). Not offsite unless the folder itself is on another machine."""

    def __init__(self, folder: str | Path):
        self.folder = Path(folder)
        self.folder.mkdir(parents=True, exist_ok=True)

    def _path(self, name: str) -> Path:
        p = (self.folder / name).resolve()
        if self.folder.resolve() not in p.parents:
            raise ValueError("path escapes the backup folder")
        return p

    def put(self, name: str, data: bytes) -> None:
        p = self._path(name)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)

    def get(self, name: str) -> bytes:
        return self._path(name).read_bytes()

    def list(self, prefix: str = "") -> list[tuple[str, int]]:
        base = self.folder.resolve()
        return sorted((str(p.relative_to(base)).replace(os.sep, "/"), p.stat().st_size) for p in base.rglob("*") if p.is_file() and str(p.relative_to(base)).replace(os.sep, "/").startswith(prefix))

    def delete(self, name: str) -> None:
        self._path(name).unlink(missing_ok=True)


def sigv4_headers(method: str, url: str, *, region: str, key_id: str, secret: str, payload: bytes = b"", now: dt.datetime | None = None, service: str = "s3",
                  extra_headers: dict | None = None) -> dict:
    """AWS Signature Version 4 request headers (verified against AWS's published test-suite vector in tests/test_offsite.py)."""
    now = now or dt.datetime.now(dt.timezone.utc)
    amz_date, date = now.strftime("%Y%m%dT%H%M%SZ"), now.strftime("%Y%m%d")
    parts = urllib.parse.urlsplit(url)
    canonical_query = "&".join(f"{urllib.parse.quote(k, safe='-_.~')}={urllib.parse.quote(v, safe='-_.~')}" for k, v in sorted(urllib.parse.parse_qsl(parts.query, keep_blank_values=True)))
    payload_hash = hashlib.sha256(payload).hexdigest()
    headers = {"host": parts.netloc, "x-amz-date": amz_date, **{k.lower(): v for k, v in (extra_headers or {}).items()}}
    if service == "s3":
        headers["x-amz-content-sha256"] = payload_hash
    signed = ";".join(sorted(headers))
    canonical_headers = "".join(f"{k}:{headers[k].strip()}\n" for k in sorted(headers))
    canonical = "\n".join([method, urllib.parse.quote(parts.path or "/", safe="/-_.~"), canonical_query, canonical_headers, signed, payload_hash])
    scope = f"{date}/{region}/{service}/aws4_request"
    to_sign = "\n".join(["AWS4-HMAC-SHA256", amz_date, scope, hashlib.sha256(canonical.encode()).hexdigest()])
    k = ("AWS4" + secret).encode()
    for part in (date, region, service, "aws4_request"):
        k = hmac.new(k, part.encode(), hashlib.sha256).digest()
    signature = hmac.new(k, to_sign.encode(), hashlib.sha256).hexdigest()
    out = {h: v for h, v in headers.items() if h != "host"}
    out["Authorization"] = f"AWS4-HMAC-SHA256 Credential={key_id}/{scope}, SignedHeaders={signed}, Signature={signature}"
    return out


class S3Compatible:
    """Path-style requests to an S3-compatible endpoint (AWS S3, Backblaze B2, Cloudflare R2)."""

    def __init__(self, endpoint: str, bucket: str, region: str, key_id: str, secret: str, *, client: httpx.Client | None = None):
        self.endpoint, self.bucket, self.region, self.key_id, self.secret = endpoint.rstrip("/"), bucket, region, key_id, secret
        self.http = client or httpx.Client(timeout=60)

    def _url(self, name: str = "", query: str = "") -> str:
        return f"{self.endpoint}/{self.bucket}" + (f"/{urllib.parse.quote(name, safe='/-_.~')}" if name else "") + (f"?{query}" if query else "")

    def _do(self, method: str, url: str, payload: bytes = b"") -> httpx.Response:
        headers = sigv4_headers(method, url, region=self.region, key_id=self.key_id, secret=self.secret, payload=payload)
        r = self.http.request(method, url, content=payload or None, headers=headers)
        r.raise_for_status()
        return r

    def put(self, name: str, data: bytes) -> None:
        self._do("PUT", self._url(name), data)

    def get(self, name: str) -> bytes:
        return self._do("GET", self._url(name)).content

    def delete(self, name: str) -> None:
        self._do("DELETE", self._url(name))

    def list(self, prefix: str = "") -> list[tuple[str, int]]:
        out, token = [], ""
        while True:
            q = "list-type=2" + (f"&prefix={urllib.parse.quote(prefix, safe='')}" if prefix else "") + (f"&continuation-token={urllib.parse.quote(token, safe='')}" if token else "")
            xml = self._do("GET", self._url(query=q)).text
            for m in re.finditer(r"<Contents>.*?<Key>(.*?)</Key>.*?<Size>(\d+)</Size>.*?</Contents>", xml, re.S):
                out.append((m.group(1), int(m.group(2))))
            nxt = re.search(r"<NextContinuationToken>(.*?)</NextContinuationToken>", xml)
            if "<IsTruncated>true</IsTruncated>" in xml and nxt:
                token = nxt.group(1)
            else:
                return sorted(out)


def configured_destination() -> Destination | None:
    folder = os.environ.get("OFFSITE_BACKUP_DIR")
    if folder:
        return LocalFolder(folder)
    need = ("OFFSITE_S3_ENDPOINT", "OFFSITE_S3_BUCKET", "OFFSITE_S3_REGION", "OFFSITE_S3_KEY_ID", "OFFSITE_S3_SECRET")
    if all(os.environ.get(k) for k in need):
        return S3Compatible(os.environ["OFFSITE_S3_ENDPOINT"], os.environ["OFFSITE_S3_BUCKET"], os.environ["OFFSITE_S3_REGION"], os.environ["OFFSITE_S3_KEY_ID"], os.environ["OFFSITE_S3_SECRET"])
    return None


# ---------------------------------------------------------------------------------------------------------- the job
def object_name(day: dt.date) -> str:
    return f"callkettle/{day:%Y}/{day:%m}/callkettle-{day:%Y-%m-%d}.db.enc"


def prune(dest: Destination, keep_daily: int = KEEP_DAILY, keep_monthly: int = KEEP_MONTHLY) -> list[str]:
    """Keep the newest `keep_daily` copies plus the first copy of each of the newest `keep_monthly` months; delete the rest."""
    names = sorted(n for n, _ in dest.list("callkettle/") if n.endswith(".db.enc"))
    dated = {}
    for n in names:
        m = re.search(r"callkettle-(\d{4}-\d{2})-(\d{2})\.db\.enc$", n)
        if m:
            dated[n] = (m.group(1), m.group(2))
    keep = set(sorted(dated)[-keep_daily:])
    firsts = {}
    for n, (month, _day) in sorted(dated.items()):
        firsts.setdefault(month, n)
    keep |= {firsts[m] for m in sorted(firsts)[-keep_monthly:]}
    removed = []
    for n in dated:
        if n not in keep:
            try:
                dest.delete(n)
                removed.append(n)
            except Exception:                    # a write-only key cannot delete: pruning is optional, never a failure
                logger.info("Could not prune %s (a write-only key cannot delete); skipping", n)
                break
    return removed


def status_from(env: dict | None = None) -> dict:
    env = env if env is not None else os.environ
    return {"configured": bool(env.get("OFFSITE_BACKUP_PUBLIC_KEY") and (env.get("OFFSITE_BACKUP_DIR") or env.get("OFFSITE_S3_BUCKET")))}


def run_offsite_backup(local_backup: Path, *, dest: Destination | None = None, public_pem: bytes | None = None, today: dt.date | None = None) -> dict:
    """Encrypt and upload one verified local backup, then list it back at the expected size. Never raises: returns {"ok": bool, ...}."""
    dest = dest or configured_destination()
    pem = public_pem or (os.environ.get("OFFSITE_BACKUP_PUBLIC_KEY") or "").encode()
    if dest is None or not pem:
        return {"ok": False, "configured": False, "problem": "offsite backup is not configured"}
    try:
        today = today or dt.datetime.now(dt.timezone.utc).date()
        blob = encrypt(Path(local_backup).read_bytes(), pem)
        name = object_name(today)
        dest.put(name, blob)
        listed = dict(dest.list(name))
        if listed.get(name) != len(blob):
            return {"ok": False, "configured": True, "problem": f"uploaded {len(blob)} bytes but the destination lists {listed.get(name)}"}
        removed = prune(dest)
        return {"ok": True, "configured": True, "object": name, "bytes": len(blob), "pruned": len(removed)}
    except Exception as exc:
        logger.exception("Offsite backup failed")
        return {"ok": False, "configured": True, "problem": f"{type(exc).__name__}: {str(exc)[:120]}"}


def restore_latest(dest: Destination, private_pem: bytes, out_path: Path) -> dict:
    """Download the newest backup, decrypt it and write it to out_path. The caller then runs ops.verify_backup on it. This is the rehearsed restore."""
    names = sorted(n for n, _ in dest.list("callkettle/") if n.endswith(".db.enc"))
    if not names:
        raise FileNotFoundError("no offsite backups found")
    latest = names[-1]
    data = decrypt(dest.get(latest), private_pem)
    Path(out_path).write_bytes(data)
    return {"object": latest, "bytes": len(data), "path": str(out_path)}
